#! /usr/bin/env python3
"""A command-line argument completer for use with Bash-like completion via
"complete". See the accompanying "zeek" shell script, and install it in one of
your system's bash_completion.d directories.
"""

# For easier forward references in type annotations -- not needed in 3.14+
from __future__ import annotations

import argparse
import enum
import glob
import os
import pathlib
import re
import shlex
import subprocess
import sys
import tempfile
import traceback

from itertools import islice
from typing import Any


class CompType(enum.Enum):
    """An enum representation of the numerical completion type values passed in
    via the COMP_TYPE environment variable."""

    # Funny numbers. They're supposed to render as individual characters
    # as well -- see the Bash manpage for details. "Normal" and "successive"
    # completions come up regularly. I haven't figuredo out the others.
    UNKNOWN = 0
    NORMAL = 9  # tab -- will complete if there's only a single possibility
    SUCCESSIVE = 63  # ? (tab tab) -- will list possible completions
    PARTIAL_WORD = 33  # !
    MODDED_WORD = 64  # @
    MENU = 37  # %


class LineContext:
    """This provides the context of the current line input: the command, the
    current word (up to the point -- for example, if the last word is "foo" and
    the cursor is at "f<cursor>oo", the current word is "f") and a possible
    previous word are passed as arguments if we're invoked via "complete -C".
    Such invocation also provides COMP_* environment variables for the whole
    line, the point offset, and the completion type, so we grab these as
    available as well.
    """

    def __init__(self, cmd: str, curr_word: str, prev_word: str):
        self.cmd = cmd
        self.curr_word = curr_word
        self.prev_word = prev_word

        self.comp_type = CompType(int(os.getenv("COMP_TYPE", "0")))
        self.line = os.getenv("COMP_LINE", "")
        self.point = os.getenv("COMP_POINT", "")

        # All words on the current line, excluding the command (the first word),
        # excluding the current word if any, but keeping quoted content intact
        # ('foo "bar baz"' turns into two words, "foo" and "bar baz"):
        self.line_words: list[str] = shlex.split(self.settled_line())[1:]

    def settled_line(self) -> str:
        """Returns the input line without any trailing word that's still
        incomplete (i.e., any non-empty self.curr_word)."""
        return self.line.removesuffix(self.curr_word)


class ZeekArg:
    """A command-line argument to Zeek, with optional additional parameters
    (such as a network interface to -i, or a debug stream to -B). A long-form
    ("--foo") is always required, a short form ("-f") is usually but not always
    available. This class stores additional information about these arguments
    and can match them completely or partially, which helps completion.
    """

    def __init__(
        self,
        longarg: str,
        shortarg: str = "",
        param: str = "",
        param_optional: bool = False,
    ):
        self.longarg = longarg  # The long-form arg, e.g. "--foo"
        self.shortarg = shortarg  # The short-form arg, e.g. "-f"
        self.param = param  # The param, e.g. "interface"
        self.param_optional = param_optional  # Whether the param is optional

        # Determine whether the argument needs a file parameter. We do this
        # heuristically based on the naming in the help output ...
        self.needs_file_param = "file" in self.param
        # ...  and with some special-casing:
        if self.longarg in ("--optimize-files", "--no-optimize-files"):
            self.needs_file_param = True

    def __str__(self) -> str:
        if self.shortarg:
            res = self.shortarg + "|" + self.longarg
        else:
            res = self.longarg
        if self.param:
            res = f"{res} {'<' if self.param_optional else ''}{self.param}{'>' if self.param_optional else ''}"
        return res

    def match(self, prefix: str) -> MatchedArg | None:
        """Returns a MatchedArg for this argument if the given prefix fits
        either the short argument or the long one. Otherwise returns None.
        """
        if self.shortarg.startswith(prefix):
            return MatchedArg(self, is_short=True)
        if prefix.startswith("--") and self.longarg.startswith(prefix):
            return MatchedArg(self, is_short=False)
        return None

    def equal(self, arg: str) -> MatchedArg | None:
        """Returns a MatchedArg for this argument if the given argument name
        fits either the short argument or the long one exactly. Otherwise
        returns None.
        """
        if self.shortarg == arg:
            return MatchedArg(self, is_short=True)
        if arg.startswith("--") and self.longarg == arg:
            return MatchedArg(self, is_short=False)
        return None


class MatchedArg:
    """An argument selected via a prefix match, either on the short or the long
    version of the argument."""

    def __init__(self, arg: ZeekArg, is_short: bool):
        self.arg = arg
        self.is_short = is_short

    def __str__(self) -> str:
        if self.is_short:
            return self.arg.shortarg
        return self.arg.longarg


class ZeekArgs:
    """This class stores all context for Zeek's available arguments. It does
    this by parsing the output of "zeek --help", including the ZEEKPATH shown in
    the output.
    """

    def __init__(self, cmd: str):
        self.cmd: str = cmd
        self.args: dict[str, ZeekArg] = {}  # indexed by long-form arg

        # A parser for the command line so we can easily parse the existing
        # line. Zeek supports things like "-C -r ..." being the same as "-Cr",
        # and can intersperse redefs and scripts anywhere betweem arguments, so
        # parsing manually gets annoying quickly.
        self.argparser = argparse.ArgumentParser(
            "zeek", add_help=False, exit_on_error=False
        )

        # The effective ZEEKPATH. We use the environment when available,
        # otherwise parse from Zeek's help output with the regex below.
        self.zeekpath: str = os.getenv("ZEEKPATH", "")
        self.zeekpath_re = re.compile(r"\$ZEEKPATH *\|.+\((.+)\)")

        # Track whether we've parsed Zeek help output so we do it only once.
        self.parsed = False

    def parse_help(self) -> bool:
        """Grabs the output of "zeek --help" via the given command, parses it
        into self.args, and populates an argparse.ArgumentParser. Returns True
        if successful, False otherwise (e.g. when the invocation failed).
        """
        if self.parsed:
            return True

        try:
            res = subprocess.run(
                (self.cmd, "--help"), capture_output=True, text=True, timeout=1
            )
        except subprocess.TimeoutExpired:
            return False

        if res.returncode != 0:
            return False

        lines = [line.lstrip() for line in res.stdout.splitlines()]
        if not lines or not lines[0].startswith("zeek version"):
            return False

        for line in lines:
            # Parse the built-in ZEEKPATH if the environment doesn't override.
            if not self.zeekpath and line.startswith("$ZEEKPATH"):
                mob = self.zeekpath_re.match(line)
                if mob is not None and len(mob.groups()) == 1:
                    self.zeekpath = mob.group(1)
                # This is currently the last line we care about in the output.
                break

            # For argument parsing, grab lines starting with a command-line
            # argument, and split those lines along "|". We should have at least
            # two resulting strings; three if the argument has short and long
            # forms. Zeek's arguments always have at least a long form
            # ("--foo"). They usually have both long and short forms. They never
            # have only a short form ("-f").
            if not line.startswith("-"):
                continue
            parts = line.split("|")
            if len(parts) < 2:
                continue

            shortarg = ""
            param = ""
            param_optional = False

            if parts[0].startswith("--"):
                # It's a long-form only argument
                longarg = parts[0].strip()
            else:
                shortarg, longarg = parts[0].strip(), parts[1].strip()

            if "[" in longarg:
                param_optional = True

            # Go from e.g "--pseudo-realtime[=<speedup>]" to
            # "--pseudo-realtime=speedup", to be broken apart below.
            for char in "[]<>":
                longarg = longarg.replace(char, "")

            # Some long forms use a space separator in the help output, others an equals sign:
            longparts = [p.strip() for p in re.split(r"[ =]", longarg)]

            if len(longparts) > 1:
                param = longparts[1]  # Things like "file", "level", or "interface"

            # We now have everything for a ZeekArg, register it:
            self.args[longparts[0]] = ZeekArg(
                longparts[0], shortarg, param, param_optional
            )

            # Parse the help output into an argparse parser:
            arg_names = [longparts[0]]
            if shortarg:
                arg_names.append(shortarg)

            arg_details: dict[str, str | int | None] = {}

            if param:
                arg_details["nargs"] = 1
                if param_optional:
                    # The value doesn't matter here, it's just so
                    # we have a default to assign when parsing:
                    arg_details["default"] = "default"
                    arg_details["nargs"] = "?"
            else:
                arg_details["action"] = "store_true"  # argparse bails on "nargs=0".

            self.argparser.add_argument(*arg_names, **arg_details)  # type: ignore

        self.parsed = True
        return True

    def parse_line(
        self, lctx: LineContext
    ) -> tuple[argparse.Namespace, list[str]] | tuple[None, None]:
        """Parse the given line context via argparse into arguments and any
        added Zeek scripts/redefs provided. Returns these as a tuple, or
        None/None in case of error.
        """
        try:
            # Tricky: we want to process lctx.line_words, i.e. the command
            # arguments on the current line, excluding the potential final
            # in-progress word. However, if the last completed word is the
            # opening of an argument that will need a parameter (say the line
            # ends in "-i " -- note the space -- missing an interface), then
            # argparse parsing will fail because a required argument isn't
            # provided. So examine that last word and strip it if it's an
            # argument that would need a subsequent parameter. If parsing fails
            # due to other stuff earlier in the line, there's nothing we can do
            # and we just won't offer completions.
            words = lctx.line_words.copy()
            if words:
                marg = self.find(words[-1])
                if marg is not None and marg.arg.param:
                    words.pop()
            return self.argparser.parse_known_args(words)
        except argparse.ArgumentError:
            # With this environment variable, fall through to the end of
            # the script so the exception gets printed out for debugging.
            if os.getenv("ZEEK_COMPLETE_EXCEPTIONS", ""):
                raise
            return None, None

    def find_by_match(self, prefix: str) -> list[MatchedArg]:
        """Returns a list of matching arguments based on prefix-matching the
        given prefix against the arguments.
        """
        res: list[MatchedArg] = []
        for zarg in self.args.values():
            match: MatchedArg | None = zarg.match(prefix)
            if match is not None:
                res.append(match)
        return res

    def find(self, arg: str) -> MatchedArg | None:
        """Returns a potential matching argument based on exact match of the
        given argument name against short or long versions. Returns None
        if no such argument exists.
        """
        for zarg in self.args.values():
            match: MatchedArg | None = zarg.equal(arg)
            if match is not None:
                return match
        return None

    def find_arg_param(self, lctx: LineContext) -> list[str]:
        """Returns possible parameters to a given argument, such as network
        interfaces for "-i".
        """
        arg = lctx.prev_word
        prefix = lctx.curr_word
        marg = self.find(arg)

        if marg is not None and marg.arg.param:
            zarg = marg.arg
            if zarg.needs_file_param:
                # Simply do regular path expansion to complete pcaps etc
                return FileCompleter().match(prefix)
            elif zarg.shortarg == "-B":
                # This takes a comma-separated list of debug streams. The
                # existing list will be in prefix ("foo,bar,", or perhaps
                # "foo,b"), which we can't use as-is to match against available
                # debug streams: focus on anything after the last comma, exclude
                # anything already selected, ...
                parts = prefix.rsplit(",", maxsplit=1)
                exclusions: set[str] = set()
                prior = ""
                if len(parts) > 1:
                    prior = parts[0] + ","
                    exclusions = set(parts[0].split(","))
                # ... and tuck anything up to and including the comma back onto
                # our returned results.
                return [
                    prior + p
                    for p in prefix_filter(
                        self._get_zeek_debugstreams(), parts[-1], exclusions
                    )
                ]
            elif zarg.shortarg == "-i":
                return prefix_filter(self._get_sys_interfaces(), prefix)
            elif zarg.shortarg == "-I":
                zgcomp = ZeekGlobalsCompleter(self, lctx)
                return zgcomp.match(prefix)
            elif zarg.shortarg == "-O":
                return prefix_filter(self._get_zeek_optimizations(), prefix)
            elif zarg.longarg in ("--optimize-funcs", "--no-optimize-funcs"):
                zgcomp = ZeekGlobalsCompleter(self, lctx, funcs_only=True)
                return zgcomp.match(prefix)

        return []

    def _get_sys_interfaces(self) -> list[str]:
        """Returns list of network interfaces on this machine.

        This works only of the psutil module is available, otherwise this returns an
        empty list.
        """
        try:
            # For a portable way to get network interfaces:
            from psutil import net_if_addrs  # type: ignore

            return net_if_addrs().keys()  # type: ignore
        except ImportError:
            pass
        return []

    def _get_zeek_debugstreams(self) -> list[str]:
        """Returns list of the possible options to -B|--debug."""
        try:
            res = subprocess.run(
                (self.cmd, "-B", "help"), capture_output=True, text=True, timeout=1
            )
        except subprocess.TimeoutExpired:
            return []

        if res.returncode != 0:
            return []

        streams: set[str] = set()

        for line in res.stderr.splitlines():
            if not line.startswith(" "):
                continue
            stream = line.strip().split(maxsplit=1)[0]
            if not stream.startswith("plugin-"):
                streams.add(stream)

        streams.add("help")  # "help" itself is not shown in the "-B help" output.

        return list(streams)

    def _get_zeek_optimizations(self) -> list[str]:
        """Returns list of the possible options to -O|--optimize."""
        try:
            res = subprocess.run(
                (self.cmd, "-O", "help"), capture_output=True, text=True, timeout=1
            )
        except subprocess.TimeoutExpired:
            return []

        if res.returncode != 0:
            return []

        opts: list[str] = []

        for line in res.stdout.splitlines():
            if not line.startswith("    "):
                continue
            opts.append(line.strip().split(maxsplit=1)[0])

        return opts


class FileTree:
    """Base class for file path completion. This works just like normal
    path expansion in your shell, based on a local prefix, and completing the
    exact prefix string you enter. Can optionally focus on Zeek scripts & JS.
    """

    # If you want .bro, you're old enough to be used to typing a lot. ;-)
    ZEEK_SUFFIXES = [".zeek", ".js"]

    def __init__(self, zeek_only: bool = False, limit: int = 1000):
        self.zeek_only = zeek_only
        self.limit = limit

    def match(self, prefix: str) -> list[str]:
        res: list[str] = []
        for path in islice(glob.glob(self.expand_prefix(prefix) + "*"), self.limit):
            p = pathlib.Path(path)
            if p.is_dir():
                # If it's a directory, we end with the separator. That
                # makes it more natural to continue to expand.
                res.append(f"{path}{os.sep}")
                continue
            if self.zeek_only and p.suffix not in self.ZEEK_SUFFIXES:
                continue
            res.append(path + " ")

        return res

    def expand_prefix(self, prefix: str) -> str:
        """Apply tile and environment variable expansion on the given file path
        prefix, and return the result."""
        return os.path.expandvars(os.path.expanduser(prefix))


class ZeekpathScriptTree(FileTree):
    """A specialization that completes relative to a given (ZEEKPATH) directory."""

    def __init__(self, path: str, limit: int = 1000):
        """Constructor. The path argument is the directory at which we root the
        tree, and limit is the maximum number of files to yield.
        """
        super().__init__(zeek_only=True, limit=limit)
        self.path = pathlib.Path(path)

    def match(self, prefix: str) -> list[str]:
        res: list[str] = []
        try:
            # If the prefix is an absolute path, pathlib-globbing it will raise
            # a NotImplementedError. Be robust:
            for p in islice(
                self.path.glob(self.expand_prefix(prefix) + "*"), self.limit
            ):
                # The path relative to the root of the tree. This ensures we get
                # paths starting from the entries of ZEEKPATH, not absolute paths.
                rpath = p.relative_to(self.path)
                # As in the base class:
                if p.is_dir():
                    res.append(f"{rpath}{os.sep}")
                elif p.suffix in self.ZEEK_SUFFIXES:
                    res.append(str(rpath) + " ")
        except NotImplementedError:
            pass
        return res


class Completer:
    """A thing that can complete content based on a string prefix."""

    def match(self, prefix: str) -> list[str]:
        return []


class FileCompleter(Completer):
    """A completer for directory-local as well as absolute-path expansion for
    any kind of file."""

    def match(self, prefix: str) -> list[str]:
        return FileTree().match(prefix)


class ScriptCompleter(Completer):
    """A completer for directory-local as well as absolute-path expansion for
    Zeek scripts."""

    def match(self, prefix: str) -> list[str]:
        return FileTree(zeek_only=True).match(prefix)


class ZeekpathScriptCompleter(Completer):
    """This attempts path expansion for Zeek scripts, based on the directories
    in ZEEPATH as well as the local directory."""

    def __init__(self, zeekpath: str):
        self.zeekpath = zeekpath
        self.roots = [ZeekpathScriptTree(path) for path in zeekpath.split(os.pathsep)]

    def match(self, prefix: str) -> list[str]:
        # This traverses all roots, as opposed to stopping after the first root
        # that produced results. This is likely more helpful to the user, but
        # risks a lengthy list of completions.
        res: list[str] = FileTree(zeek_only=True).match(prefix)
        for root in self.roots:
            res.extend(root.match(prefix))
        return res


class ZeekGlobalsCompleter(Completer):
    SCRIPT = """
event zeek_init() &priority=10000 {
    for ( n, id in global_ids() )
        if ( @CONDITIONS@ )
            print fmt("%s %s", n, id$type_name);
    exit(0);
}
"""

    def __init__(
        self,
        args: ZeekArgs,
        lctx: LineContext,
        redefables_only: bool = False,
        funcs_only: bool = False,
    ):
        self.args = args
        self.lctx = lctx
        self.redefables_only = redefables_only
        self.funcs_only = funcs_only

    def match(self, prefix: str) -> list[str]:
        # We need to invoke Zeek so that it actually runs through initialization
        # (i.e., not just in parse mode), possibly in bare mode if requested,
        # while ensuring exit right after we print globals. Scan the command
        # line for potential bare mode and any non-options (which should be
        # scripts or redefs), keep only these, and tuck on our script.
        results = self.args.parse_line(self.lctx)

        if results[0] is None:
            # The parse failed -- must be something pretty basic.
            return []

        parsed_args: argparse.Namespace = results[0]
        scripts_and_redefs: list[str] = results[1]
        cmd: list[str] = [self.args.cmd]

        if parsed_args.bare_mode:
            cmd.append("-b")

        for script_or_redef in scripts_and_redefs:
            cmd.append(script_or_redef)

        cmd.extend(["-e", self.get_script()])

        try:
            # Run Zeek in an auto-deleted tempdir in case it generates files:
            with tempfile.TemporaryDirectory(prefix="zeek-complete-") as tmpdir:
                res = subprocess.run(
                    cmd, cwd=tmpdir, capture_output=True, text=True, timeout=2
                )
        except subprocess.TimeoutExpired:
            return []

        if res.returncode != 0:
            return []

        globals: list[str] = []

        for glbl in res.stdout.splitlines():
            try:
                name, typ = glbl.strip().split(maxsplit=1)
                if name.startswith(prefix):
                    # Experimental: include type info in tab-tab output,
                    # ie. when listing multiple potential matches. Not
                    # sure whether to keep this, might be confusing.
                    if self.lctx.comp_type == CompType.SUCCESSIVE:
                        globals.append(f"{name}=<{typ}>")
                    else:
                        globals.append(name + "=")
            except ValueError:
                continue

        return globals

    def get_script(self) -> str:
        """Returns a minified string for the globals-printing Zeek script."""
        conditions = []

        # Populate the globals-filtering if-condition depending on flags:
        if self.redefables_only:
            conditions.append("id$redefinable")
        if self.funcs_only:
            conditions.append('starts_with(id$type_name, "function(")')
        if not conditions:
            conditions.append("T")

        script = re.sub(r"@CONDITIONS@", "&&".join(conditions), self.SCRIPT)
        return re.sub(r"\s+", " ", script)


def prefix_filter(
    lst: list[str], prefix: str, exclusions: set[str] = set()
) -> list[str]:
    """Filters the given list down to items starting with the given prefix. Any
    exclusions must match the list items completely and are eliminted prior to
    prefix-matching."""
    return [
        item for item in lst if item not in exclusions and str(item).startswith(prefix)
    ]


def print_list(lst: list[Any]) -> bool:
    """Given a nonempty list of items, prints each and returns True; otherwise,
    returns False."""
    if lst:
        for item in lst:
            print(str(item))
        return True
    return False


def main() -> int:
    cmd, curr_word, prev_word = (sys.argv + ["", "", ""])[1:4]
    if not cmd:
        # We may not have a current or previous word, but if we don't have a
        # command, we're likely not invoked via "complete -C". Exit without
        # error; that way an argument-less invocation can be used to test
        # whether the script is available.
        return 0

    ctx = LineContext(cmd, curr_word, prev_word)
    zargs = ZeekArgs(ctx.cmd)

    # First, try simple path-based script completion. For this we need to
    # parsing of Zeek output. This is similar to standard shell expansion, but
    # doing this ourselves allows os to control ordering relative to other
    # completion strategies.
    if (
        ctx.curr_word
        and not ctx.curr_word.startswith("-")
        and not ctx.curr_word.endswith("=")
    ):
        lsc = ScriptCompleter()
        scripts = lsc.match(ctx.curr_word)
        if print_list(scripts):
            return 0

    # With the start of a command-line argument, apply argument completion:
    if ctx.curr_word.startswith("-"):
        if not zargs.parse_help():
            return 1
        matches = zargs.find_by_match(ctx.curr_word)
        if print_list(matches):
            return 0

    # Next, if the previous word is an argument, and the current isn't, this
    # might be a parameter to the argument, such as a network interface to -i,
    # or a pcap to -r.
    if ctx.prev_word.startswith("-") and (
        not ctx.curr_word or not ctx.curr_word.startswith("-")
    ):
        if not zargs.parse_help():
            return 1
        params = zargs.find_arg_param(ctx)
        if print_list(params):
            return 0

    # If it looks file-like, try script path completion based on ZEEKPATH:
    if (
        ctx.curr_word
        and not ctx.curr_word.startswith("-")
        and not ctx.curr_word.endswith("=")
    ):
        if not zargs.parse_help():
            return 1
        zscomp = ZeekpathScriptCompleter(zargs.zeekpath)
        scripts = zscomp.match(ctx.curr_word)
        if print_list(scripts):
            return 0

    # And at last, try redefing globals.
    if ctx.curr_word:
        if not zargs.parse_help():
            return 1
        zgcomp = ZeekGlobalsCompleter(zargs, ctx, redefables_only=True)
        glbls = zgcomp.match(ctx.curr_word)
        if print_list(glbls):
            return 0

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        # Sweep this under the rug unless the user has asked to see backtraces.
        if os.getenv("ZEEK_COMPLETE_EXCEPTIONS", ""):
            print("\n*** zeek-complete failed unexpectedly:", file=sys.stderr)
            traceback.print_exc(file=sys.stderr)
    except KeyboardInterrupt:
        # Just error out if the user ctrl-c's while we run things.
        pass
    sys.exit(1)
